# Generated by Django 4.0.1 on 2022-01-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование сми')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование производителя')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Stands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('square', models.IntegerField(default=10, verbose_name='Площадь м2')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_supplier', to='base.supplier', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Стенд',
                'verbose_name_plural': 'Стенды',
            },
        ),
    ]
