# Generated by Django 4.0.1 on 2022-01-17 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media_id', to='base.media', verbose_name='сми'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
